{% set name = "aws-c-common" %}
{% set version = "0.4.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5007ffedc64f5f979d36e223bbd80a5c03ecaca151c003944b63e06f1b2845ff
  patches:
    - no-werror.patch
    - 0001-Don-t-hardcode-the-CoreFoundation-path.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("aws-c-common", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja

outputs:
  - name: aws-c-common
    script: install.sh
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - ninja
    test:
      commands:
        - test -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}  # [unix]
        - test ! -f $PREFIX/lib/libaws-c-common.a  # [unix]
        - test -f $PREFIX/include/aws/common/config.h  # [unix]
        - test -f $PREFIX/lib/cmake/AwsCFlags.cmake  # [unix]
        # Check for the non-existence of -Werror in the CFLAGS
        - "! grep Werror $PREFIX/lib/cmake/AwsCFlags.cmake"  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\aws-c-common.dll exit 1  # [win]
        - if exist %PREFIX%\\Library\\lib\\aws-c-common.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\include\\aws\\common\\config.h exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\AwsCFlags.cmake exit 1  # [win]

  - name: aws-c-common-static
    script: install.sh
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - ninja
    test:
      commands:
        - test ! -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}  # [unix]
        - test -f $PREFIX/lib/libaws-c-common.a  # [unix]
        - test -f $PREFIX/include/aws/common/config.h  # [unix]
        - test -f $PREFIX/lib/cmake/AwsCFlags.cmake  # [unix]
        # Check for the non-existence of -Werror in the CFLAGS
        - "! grep Werror $PREFIX/lib/cmake/AwsCFlags.cmake"  # [unix]
        - if exist %PREFIX%\\Library\\bin\\aws-c-common.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\aws-c-common.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\include\\aws\\common\\config.h exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\AwsCFlags.cmake exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-common
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.

extra:
  recipe-maintainers:
    - xhochy
    - davidbrochart
