schema_version: 1

context:
  name: aws-c-common
  version: "1.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/awslabs/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 3c204c2a457b0282dd7d1e7edf14ff81bced6928199d12839103e2d4311893a7
  patches:
    - 0001-Explicitly-remove-Werror.patch

build:
  number: 0

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  run_exports:
    # https://github.com/awslabs/aws-c-common/blob/main/VERSIONING.md
    - ${{ pin_subpackage("aws-c-common", upper_bound="x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-common${SHLIB_EXT}
          - test -f $PREFIX/include/aws/common/config.h
          - test -f $PREFIX/lib/cmake/aws-c-common/modules/AwsCFlags.cmake
          - "! grep Werror $PREFIX/lib/cmake/AwsCFlags.cmake"
      - if: win
        then:
          - if not exist %PREFIX%\\Library\\bin\\aws-c-common.dll exit 1
          - if not exist %PREFIX%\\Library\\include\\aws\\common\\config.h exit 1
          - if not exist %PREFIX%\\Library\\lib\\cmake\\aws-c-common\\modules\\AwsCFlags.cmake exit 1

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Core c99 package for AWS SDK for C. Includes cross-platform primitives, configuration, data structures, and error handling.
  homepage: https://github.com/awslabs/aws-c-common
  repository: https://github.com/awslabs/aws-c-common

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
